### PR TITLE
Deactivate CONCOCT in most tests

### PR DESCRIPTION
**Pull request by jfy133**
Except bin refinement, where it is anyway most relevent.

This will allow most tests not take ages to complete. We could also further separate this so we do an extremely minimal run and only run CONCOCT (no other downstream steps), if these tests remain too length.

### CODE REVIEW

**Review by d4straub — COMMENTED** [review]
Looks good to me, but why is the `test_ancient_dna` test failing? Dont get it.

**Comment by jfy133** [comment]
No, there is some weird corruption thing going on I think. @skrakau has also observed this.... Not sure why. I'll be looking into it next week when I'm back from holiday

**Comment by jfy133** [comment]
Ok so the issue is for the aDNA run we bizarrely get a join mismatch:

https://github.com/nf-core/mag/actions/runs/3831704693/jobs/6609861357#step:4:271

But this is separate from the aDNA 'subworkflow'... 

(Cc @skrakau )

**Comment by jfy133** [comment]
@d4straub @skrakau this is now working :) linting failure is because template has not been merged yet, but the rest should be OK if you're happy  with it

**Comment by d4straub** [comment]
Hm, tests failed, I restarted them.

**Review by d4straub — APPROVED** [review]
Looks good to me

**Pull request merged**
