### PR TITLE
Fixed Update description of additional Bowtie2 and SPAdes parameters …

### PR DESCRIPTION
**Pull request by willros**
…used in command line (issue #411)

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mag/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/mag _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by d4straub — APPROVED** [review]
Thanks, looks good to me!
If you want to merge the PR yourself, you might have to join nf-core on github first, see https://nf-co.re/join#github. Otherwise post here and anone else can merge it after tests pass.

**Review by d4straub — COMMENTED** [review]
Oh, but you might want to add your contribution to `CHANGELOG.md`!

**Comment by willros** [comment]
> Thanks, looks good to me! If you want to merge the PR yourself, you might have to join nf-core on github first, see https://nf-co.re/join#github. Otherwise post here and anone else can merge it after tests pass.

Someone else can merge it for now! Thanks,
William

**Comment by jfy133** [comment]
Thanks @willros !!

**Pull request merged**
