### PR TITLE
Bump GTDBTk to v2.4.0

### PR DESCRIPTION
**Pull request by dialvarezs**
Update GTDBTk module to latest version, and update `summary_gtdbtk.py` to hande column name changes.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mag/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/mag _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jfy133** [comment]
Thank you very much @dialvarezs ! A very nice thing to come abck from weekend too :sunglasses: 

I',m going to run a test on a HPC (as we can't test GTDB on GitHub due to the massive database file), and if that works I will merge this in :)

**Comment by dialvarezs** [comment]
Don't worry, and thanks for the review! I forgot to update the db parameter 😅.
I've run MAG with this modification a few times over the last month in our HPC, and so far, everything has worked without any issues.

**Comment by jfy133** [comment]
Oh nice! What amount of memory were you generally having to use to get it to run? Given the database is like 40gb larger than the other I wonder if we need to bump the minimum amount

**Comment by dialvarezs** [comment]
Good question. I'm using the default 128GB, and until now I have seen no failed jobs. Now, looking into it, Slurm reports a MaxRSS of around 10GB, while Nextflow reports about 300GB. I think this is because pplacer uses RAM as disk cache, and switches to scratch space if memory is not enough.

**Comment by jfy133** [comment]
OK cool, thanks for that! I've discovered a bug ion the nf-core module (because our test data MAGs doesn't get hits in the GTDB database funnily enough), but once I've fixed that I'll update the module in your PR, run my test again, and then I thin kwe are pretty much good to go :)

**Review by jfy133 — APPROVED** [review]
LGTM And works for me too, thank you @dialvarezs ! Impactful first contribution :muscle:

**Pull request merged**
