### PR TITLE
Add busco_clean parameter 

### PR DESCRIPTION
**Pull request by prototaxites**
Following https://github.com/nf-core/mag/issues/341: Added the parameter flag `params.busco_clean` and corresponding code in `workflow/modules/busco.nf`, to allow cleaning up of BUSCO work directories following successful execution to reduce file numbers.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mag/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/mag _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by d4straub** [comment]
@nf-core-bot fix linting

**Comment by d4straub** [comment]
Thanks for the PR!
Could you add a note to [CHANGELOG.md](https://github.com/nf-core/mag/blob/dev/CHANGELOG.md) & activate it in a test profile (e.g. by adding `busco_clean = false` to [test.config](https://github.com/nf-core/mag/blob/master/conf/test.config))?

**Comment by prototaxites** [comment]
Done! I didn't fork off dev (realising now this was a mistake) so there's some changelog conflicts - hopefully they're not difficult to resolve. This is all rather new to me!

**Comment by d4straub** [comment]
Yes, nf-core pipelines are developed on the dev branch, not master branch. The file changes are fine now. Lets see how the CI tests run.

**Review by skrakau — COMMENTED** [review]
Hi, I am just wondering, is there a reason why you do not just delete the whole `BUSCO` and and `augustus_config` folders? The relevant BUSCO output files were anyway copied/moved before, or am I missing something here?

**Comment by prototaxites** [comment]
There's other output in the `BUSCO` directory, log files in particular, that I thought it was best to leave, in case someone needs to go digging through the work directory to inspect them for some reason (some kind of silent error, maybe).

**Review by skrakau — APPROVED** [review]
Didn't test it, but looks good to me

**Comment by d4straub** [comment]
I'm going to merge this since nobody else seems to do that ;)

**Pull request merged**
