### PR TITLE
Bump 1.2.0dev

### PR DESCRIPTION
**Pull request by skrakau**
Bump 1.2.0dev

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated
- [ ] If necessary, also make a PR on the [nf-core/mag branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/mag)

### CODE REVIEW

**Comment by skrakau** [comment]
Applied changes by @KevinMenden from https://github.com/nf-core/tools/pull/774 to avoid deprecated env usage and get CI tests working again.

**Review by d4straub — APPROVED** [review]
Looks good to me! Was before already wondering why checks are failing.

**Comment by skrakau** [comment]
me too :)

**Comment by KevinMenden** [comment]
There was an error in the changes I made, you'll have to change the code slightly:
See here:
https://github.com/nf-core/tools/pull/777

Basically exchange `env.GIT_DIFF` by `env.MATCHED_FILES` otherwise the docker image gets build all the time

**Comment by skrakau** [comment]
Thanks a lot @KevinMenden , was just about to change that :)

**Comment by KevinMenden** [comment]
Sorry for the inconvenience :)

**Comment by skrakau** [comment]
Thanks to you for updating the CI and keeping us informed!

**Pull request merged**
