### PR TITLE
Patch release 2.2.1

### PR DESCRIPTION
**Pull request by jfy133**
- Fixes a bad pydamage bug where results files were overwritten
- (Hopefully) fixes a too many symlinks during a gunzip step

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mag/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/mag _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by mashehu — APPROVED** [review]

**Review by d4straub — APPROVED** [review]
LGTM

**Review by FriederikeHanssen — COMMENTED** [review]
no version update in the readme or the docker container?

**Comment by jfy133** [comment]
> no version update in the readme or the docker container?

These are DSL1 things, no?

At least `nf-core bump-versions` didn't update these, and I don't see neither pipeline version referenced in the README and no docker file...?

**Comment by FriederikeHanssen** [comment]
> > no version update in the readme or the docker container?
> 
> These are DSL1 things, no?
> 
> At least `nf-core bump-versions` didn't update these, and I don't see neither pipeline version referenced in the README and no docker file...?

🤦‍♀️ for a brief moment thought it was dsl1. never mind.

**Pull request merged**
