### PR TITLE
Add mimetype to input parameter in schema

### PR DESCRIPTION
**Pull request by drpatelh**

### CODE REVIEW

**Review by jfy133 — APPROVED** [review]
LGTM for me @drpatelh 

However maybe you can describe why it's needed/presumably not yet in template? (I remember seeing a discussion about this somewhere and it's something to with tower, but it woudl be good to document here for the future)

**Comment by drpatelh** [comment]
Thanks @jfy133 ! This allows using the pipeline with Datasets on Nextflow Tower. We need to be explicit about the `mimetype` so the Dataset is rendered when launching the pipeline.

**Comment by jfy133** [comment]
I guess should add this to other pipelines too :eyes:

**Comment by drpatelh** [comment]
I created mass PRs updating other pipelines too :)

**Pull request merged**
