### PR TITLE
Allow CAT_DB to take a directory containing the CAT database

### PR DESCRIPTION
**Pull request by prototaxites**
One last little one from me before the holidays. Allow CAT_DB to take a directory containing the CAT database, rather than just a tar.gz file - when working with a local copy of the database, saves approximately an hour on the tar.gz extraction. 

Also fixes an issue with the cat_official_taxonomy parameter I added before, where I had a brain fart writing the code and included the wrong flag in the `CAT add_names` command.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mag/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/mag _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by prototaxites** [comment]
@nf-core-bot fix linting

**Review by d4straub — APPROVED** [review]
LGTM, but I didnt actually test it, did you?

**Comment by prototaxites** [comment]
It was before Christmas, but I did test it and it works happily both with a zip or a directory - CAT ran happily either way. Can re-run if you think it's needed?

**Comment by d4straub** [comment]
I think thats fine, feel free to merge it ;)

**Pull request merged**
