### PR TITLE
Add taxonomic info #19

### PR DESCRIPTION
**Pull request by d4straub**
Work-in-progress, added:
- centrifuge on Illumina reads
- krakren2 on Illumina reads
- krona plots for centrifuge & krakren2 results
- CAT for taxonomy of genomic bins

Currently testing.

There are no changes in the test configs (yet), the taxonomic databases required are huge but we could produce our own ones.

### CODE REVIEW

**Comment by d4straub** [comment]
Alright, this seems to work so far, #19 is solved.

For test that include the taxonomic classification, small classification databases for centrifuge, kraken2 and CAT would be required. Just don't know how to do that best.

**Comment by HadrienG** [comment]
Nicely done!

I've added a test database for centrifuge. I'm struggling to create a small database for kraken2 but will keep trying.

Best,
Hadrien

**Comment by HadrienG** [comment]
I'm done with the kraken2 test database. For CAT they have no instructions for building a custom database so I'd skip the test.

@d4straub are we ready to merge to dev?

**Comment by d4straub** [comment]
Yes, we are ready, thanks for adding the tests!

The [`CAT prepare`](https://github.com/dutilh/CAT#generating-the-database-files-yourself) does not allow to specify the database it uses for creating a classification database, it seems. I also don't know how we could do a small test classification database.

**Pull request merged**
