### PR TITLE
Update workflow overview figure

### LINKED ISSUE #248: Update workflow figure
Update workflow figure with
- Prodigal for protein-coding gene prediction https://github.com/nf-core/mag/pull/240
- Prokka for genome annotation of bins https://github.com/nf-core/mag/pull/245

Also, in my opinion, a figure that resembles more the shape of a presentation slide is more convenient. But thats obviously just personal taste.

### PR DESCRIPTION
**Pull request by AntoniaSchuster**
Updated workflow figure to include Prodigal and Prokka. Closes #248.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mag/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/mag _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by d4straub** [comment]
Nice, but have a few comments:
- `PROKKA` should not be in the same square as `CAT` & `GTDB-tk`, because its not related and needs no separate `DB`, a separate square for `PROKKA` would be better I think
- short read and long read QC elements were before placed at same height for similar functions (intentionally, I guess), but are mixed now. I.e. fastp = porechop, Remove PhiX = NanoLyse, FastQC = NanoPlot (but host read removal & Filtlong have no counterparts), would be good to have those ordered on their function again
- the `DB` below `Binning` is actually for BUSCO, thats not clear any more (not sure how to solve)

**Comment by d4straub** [comment]
Great! Now I have one more idea: the nf-core/mag logo is left at the bottom and thereby making the whole figure larger. If it were at the left bottom (but higher, there seems more space) than the figure area could be made smaller, right? eager and ampliseq both keep the license info at the left lower corner, not sure if that matters, but it could be kept there I think.
My aim is to decrease figure size (ideally to a minimum, as least white space as possible) while having all processes represented properly.

**Comment by AntoniaSchuster** [comment]
I couldn't place it at the bottom without adding to the size, do you think upper right is also fine?

**Review by d4straub — APPROVED** [review]
Looks fine to me, thanks!

**Comment by AntoniaSchuster** [comment]
I realised that the figure was very small now in the README.md, I changed the width, is that ok?

**Comment by d4straub** [comment]
Seems fine to me. I kept the figure on 60% for ampliseq as well, but I agree that its quite small.

**Pull request merged**
