### PR TITLE
Add social preview image

### PR DESCRIPTION
**Pull request by MaxUlysse**
- Add social preview image

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/mag branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/mag)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/mag/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by skrakau** [comment]
Hi,

I am trying to add Github Actions tests to solve the problem above, but as probably expected run into the template linting problem.

Do you know why there is no Template PR created by the nf-core bot for this pipeline? Does one need to trigger this manually or is there a reason this is not done yet?

**Comment by ewels** [comment]
It looks like the last sync [failed spontaneously](https://github.com/nf-core/tools/runs/458082607?check_suite_focus=true#step:6:229):

```
INFO: Syncing nf-core/mag

ERROR: GitHub API returned code 404: 
{
    "message": "Not Found",
    "documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request"
}

ERROR: Sync failed for nf-core/mag:
GitHub API returned code 404: 
{
    "message": "Not Found",
    "documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request"
}
```

I'm not sure why these 404 errors occur - they seem to be basically random as far as I can tell. This sync PR will have to be done manually now anyway, or wait for the next release of tools.

Phil

**Comment by skrakau** [comment]
Thanks for the info! Is there a release of tools planned soon?

**Comment by ewels** [comment]
Not super soon - there are still quite a few issues that I would like to get sorted before we push the next release: https://github.com/nf-core/tools/milestone/7 (improving the automated sync, for example).

**Pull request merged**
