### PR TITLE
Enable stricter filtering for the aDNA assembly workflow

### PR DESCRIPTION
**Pull request by alexhbnr**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] Make sure your code lints (`nf-core lint`).

This PR enables the possibility to apply stricter filtering criteria to the modules `freebayes` and `bcftools view` as part of the aDNA assembly submodule.

### CODE REVIEW

**Review by jfy133 — APPROVED** [review]
LGTM from aDNA point of view. Welcome to Nextflow ;)

**Comment by jfy133** [comment]
@alexhbnr you need to update the json schema to get nf-core linting to pass.

You would need to clone the repo, enter it and run [`nf-core schema build`](https://nf-co.re/tools/#pipeline-schema) to access the editor (slightly less tricky than modifying teh json itself). @maxibor can show you how if necessary

image

**Comment by jfy133** [comment]
@alexhbnr 

```
Command executed:

  bcftools view \
      --output test_minigut.filtered.vcf.gz \
       \
       \
       \
      -v snps,mnps -i 'QUAL>=30 || (QUAL>=20 && FORMAT/AO>=3' \
      --threads 2 \
      test_minigut.vcf.gz
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:ANCIENT_DNA_ASSEMLY_VALIDATION:BCFTOOLS_VIEW":
      bcftools: $(bcftools --version 2>&1 | head -n1 | sed 's/^.*bcftools //; s/ .*$//')
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  Could not parse the expression: [QUAL>=30 || (QUAL>=20 && FORMAT/AO>=3]
  ```
  
  You may need to do some escaping, if the command  looks funky

**Comment by alexhbnr** [comment]
Thanks, @jfy133 , I will see how to escape this. Can I execute these tests locally, too?

**Review by jfy133 — APPROVED** [review]
Taking the liberty to approve and merge as this only effects the aDNA workflow (pinging @d4straub @skrakau to keep you aware)

**Pull request merged**
