### PR TITLE
Run CAT on unbinnned contigs as well as binned contigs

### LINKED ISSUE #125: Apply CAT also on unbinned contigs
Currently CAT is only applied to MetaBAT bins for taxonomic classification. Maybe it would be useful to apply it on whole assemblies / also on unbinned contigs.

### PR DESCRIPTION
**Pull request by jfy133**
Closes #125 

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mag/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/mag _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by d4straub** [comment]
Did you test that? Maybe I misunderstood, but doesnt your change mean that also _all_ unbinned contigs (potentially _millions_) are classified by CAT? If I am right, CAT will be unusable for larger (and not very well assembled & binned) assemblies because it will take around >=1000x longer. This would need to be optional or only contigs above a specific length threshold (that would be adjustable) or such.

**Comment by jfy133** [comment]
> 
Did you test that? Maybe I misunderstood, but doesnt your change mean that also all unbinned contigs (potentially millions) are classified by CAT? If I am right, CAT will be unusable for larger (and not very well assembled & binned) assemblies because it will take around >=1000x longer. This would need to be optional or only contigs above a specific length threshold (that would be adjustable) or such.

On the test data yes, not on real data (I dont have any at hand). Note that the 'unbinned' means the contigs considered 'good' from [split_fasta](https://github.com/nf-core/mag/blob/4b215b7939f25919d7a9dda23cdd4f793b5859a9/subworkflows/local/binning.nf#L197-L198), so there is a certain level of filtering going on there. It's not just any random contig.

I could make it optional, but maybe it would be to discuss on #125 then before I continue, if this is not sufficient?

**Comment by d4straub** [comment]
I see, thanks, I didnt make the connection! Indeed, then "only" contigs that are above `--min_length_unbinned_contigs` are added, i.e. by default >=1.000.000 bp, that seems good!

**Review by d4straub — APPROVED** [review]
LGTM!

**Comment by jfy133** [comment]
> I see, thanks, I didnt make the connection! Indeed, then "only" contigs that are above --min_length_unbinned_contigs are added, i.e. by default >=1.000.000 bp, that seems good!

Correct! Basically the same input for e.g. BUSCO and other dowsntream tools :)

**Pull request merged**
